api:
    resource: '.'
    type:     'api_platform'
    prefix:   '/api'

api_login_check:
    path: /api/login_check

api_refresh_token:
    path:     /api/token_refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }

api_upload:
    path: /api/admin/upload
    methods: [POST]
    defaults:
        _controller: AppBundle:Upload:upload

#fos_user_security:
#    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

PrestaSitemapBundle:
    resource: "@PrestaSitemapBundle/Resources/config/routing.yml"
    prefix:   /

contact:
    path: /contact
    methods: [POST]
    defaults:
        _controller: AppBundle:Contact:submit

app:
    path:     /{path}
    defaults:
        _controller: AppBundle:Index:index
        path: /
        permanent: true
    requirements:
        path: ".+"
